# dbt_project.yml

name: 'airbnb_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbnb_project:
    staging:
      +materialized: view
      +schema: silver 
    silver:
      clean:
        +schema: silver
        host:
          +materialized: incremental
        lga_suburb:
          +materialized: table
        listing:
          +materialized: incremental
        property:
          +materialized: incremental
        reference:
          +materialized: table          
    gold:
      +schema: gold
      datamart:
        +materialized: view
      dim:
        +materialized: table
      fact:
        +materialized: table
      reference:
        +materialized: table