version: 2

sources:
  - name: bronze
    schema: bronze
    description: "Raw data from Airbnb, Census, and LGA mapping sources."
    tables:
      - name: listings_bronze
      - name: census_g01_nsw_lga_bronze
      - name: census_g02_nsw_lga_bronze
      - name: nsw_lga_code_bronze
      - name: nsw_lga_suburb_bronze

